
LOCAL_SRC_FILES := \
		SensorHubOpCodeExtrator.cpp

LOCAL_CFLAGS := -DLOG_TAG=\"SensorHubDrvConfig\"

ifneq ($(strip $(SENSOR_HUB_ACCELEROMETER)), $(filter $(SENSOR_HUB_ACCELEROMETER), null))
OPCODE_FILE := $(foreach s, $(SENSOR_HUB_ACCELEROMETER), accelerometer/accelerometer_$(s).cpp)
LOCAL_SRC_FILES += $(OPCODE_FILE)

SENSOR_FLAG := $(foreach s, $(SENSOR_HUB_ACCELEROMETER), -DSENSORHUB_WITH_ACCELEROMETER_$(s))
LOCAL_CFLAGS += $(SENSOR_FLAG)
LOCAL_CFLAGS += -DSENSORHUB_WITH_ACCELEROMETER
endif

ifneq ($(strip $(SENSOR_HUB_GYROSCOPE)), $(filter $(SENSOR_HUB_GYROSCOPE), null))
OPCODE_FILE := $(foreach s, $(SENSOR_HUB_GYROSCOPE), gyroscope/gyroscope_$(s).cpp)
LOCAL_SRC_FILES += $(OPCODE_FILE)

SENSOR_FLAG := $(foreach s, $(SENSOR_HUB_GYROSCOPE), -DSENSORHUB_WITH_GYROSCOPE_$(s))
LOCAL_CFLAGS += $(SENSOR_FLAG)
LOCAL_CFLAGS += -DSENSORHUB_WITH_GYROSCOPE
endif

ifneq ($(strip $(SENSOR_HUB_LIGHT)), $(filter $(SENSOR_HUB_LIGHT), null))
OPCODE_FILE := $(foreach s, $(SENSOR_HUB_LIGHT), light/light_$(s).cpp)
LOCAL_SRC_FILES += $(OPCODE_FILE)

SENSOR_FLAG := $(foreach s, $(SENSOR_HUB_LIGHT), -DSENSORHUB_WITH_LIGHT_$(s))
LOCAL_CFLAGS += $(SENSOR_FLAG)
LOCAL_CFLAGS += -DSENSORHUB_WITH_LIGHT
endif

ifneq ($(strip $(SENSOR_HUB_MAGNETIC)), $(filter $(SENSOR_HUB_MAGNETIC), null))
OPCODE_FILE := $(foreach s, $(SENSOR_HUB_MAGNETIC), magnetic/magnetic_$(s).cpp)
LOCAL_SRC_FILES += $(OPCODE_FILE)

SENSOR_FLAG := $(foreach s, $(SENSOR_HUB_MAGNETIC), -DSENSORHUB_WITH_MAGNETIC_$(s))
LOCAL_CFLAGS += $(SENSOR_FLAG)
LOCAL_CFLAGS += -DSENSORHUB_WITH_MAGNETIC
endif

ifneq ($(strip $(SENSOR_HUB_PROXIMITY)), $(filter $(SENSOR_HUB_PROXIMITY), null))
OPCODE_FILE := $(foreach s, $(SENSOR_HUB_PROXIMITY), proximity/proximity_$(s).cpp)
LOCAL_SRC_FILES += $(OPCODE_FILE)

SENSOR_FLAG := $(foreach s, $(SENSOR_HUB_PROXIMITY), -DSENSORHUB_WITH_PROXIMITY_$(s))
LOCAL_CFLAGS += $(SENSOR_FLAG)
LOCAL_CFLAGS += -DSENSORHUB_WITH_PROXIMITY
endif

ifneq ($(strip $(SENSOR_HUB_PRESSURE)), $(filter $(SENSOR_HUB_PRESSURE), null))
OPCODE_FILE := $(foreach s, $(SENSOR_HUB_PRESSURE), pressure/pressure_$(s).cpp)
LOCAL_SRC_FILES += $(OPCODE_FILE)

SENSOR_FLAG := $(foreach s, $(SENSOR_HUB_PRESSURE), -DSENSORHUB_WITH_PRESSURE_$(s))
LOCAL_CFLAGS += $(SENSOR_FLAG)
LOCAL_CFLAGS += -DSENSORHUB_WITH_PRESSURE
endif
